spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bus_management?characterEncoding=utf8&serverTimezone=GMT%2B8&Unicode=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    encoding: UTF-8
server:
  port: 8080
